version: '3.8'

services:
  vuejs:
    build: .
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: vuejs
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"